name: CI_CD_FW

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  use-reusable-workflow:
    uses: sarafogo/pipeline_templates/.github/workflows/build.yml@main
    with:
      secrets: inherit
