name: CI_CD_FW

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      enableSonar:
        type: boolean
        description: "Habilitar etapa do Sonar"
        required: false
        default: false

jobs:
  use-reusable-workflow:
    uses: sarafogo/pipeline_templates/.github/workflows/build.yml@main
    with:
      enableSonar: ${{ github.event.inputs.enableSonar }}
    secrets: inherit

